# Generated by Django 3.2 on 2023-03-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230319_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
    ]
